version: 2.1
executors:
  default:
    docker:
    - image: circleci/golang:1.16.5

aliases:
- &restore_cache
  restore_cache:
    key: go-mod-v1-{{ checksum "go.sum" }}
- &save_cache
  save_cache:
    key: go-mod-v1-{{ checksum "go.sum" }}
    paths:
      - "/go/pkg/mod"

jobs:
    check-boilerplate:
      executor:
        name: default
      steps:
      - checkout
      - run: ./scripts/verify-boilerplate.sh

    push-docker-pr:
        executor:
            name: default
        steps:
        - checkout
        - setup_remote_docker
        - run: make build-image
        - run: ./scripts/push-docker-pr.sh
        - run:
            name: Re-run Docker Push if fail
            command: |
                sleep 20
                ./scripts/push-docker-pr.sh
            when: on_fail

    push-docker:
        executor:
            name: default
        steps:
        - checkout
        - setup_remote_docker
        - run: make build-image
        - run: ./scripts/push-docker.sh
        - run:
            name: Re-run Docker Push if fail
            command: |
                sleep 20
                ./scripts/push-docker.sh
            when: on_fail

    test:
        docker:
        - image: circleci/golang:1.16.2
          environment:
            CLOUD_DATABASE=postgres://cloud_test@localhost:5432/cloud_test?sslmode=disable
        - image: circleci/postgres:11.2-alpine
          environment:
            POSTGRES_USER: awat_test
            POSTGRES_DB: awat_test
        - image: minio/minio:RELEASE.2021-06-17T00-10-46Z-28-gac7697426
          environment:
          - MINIO_ROOT_USER=minio
          - MINIO_ROOT_PASSWORD=miniostorage
          command:
          - server
          - /tmp/
          - --console-address
          - :8888
        executor:
          name: default
        steps:
          - checkout
          - run: make test

workflows:
  version: 2
  ci-build:
    jobs:
    - check-boilerplate
    - test
    - push-docker-pr:
        context: matterbuild-docker
        requires:
          - test
          - check-boilerplate
