version: 2.1
executors:
  default:
    docker:
    - image: cimg/go:1.17.6

aliases:
- &restore_cache
  restore_cache:
    key: go-mod-v1-{{ checksum "go.sum" }}
- &save_cache
  save_cache:
    key: go-mod-v1-{{ checksum "go.sum" }}
    paths:
      - "/go/pkg/mod"

jobs:
    check-boilerplate:
      executor:
        name: default
      steps:
      - checkout
      - run: ./scripts/verify-boilerplate.sh

    push-docker-pr:
        executor:
            name: default
        steps:
        - checkout
        - setup_remote_docker
        - run: make build-image
        - run: make test-image
        - run: ./scripts/push-docker-pr.sh
        - run:
            name: Re-run Docker Push if fail
            command: |
                sleep 20
                ./scripts/push-docker-pr.sh
            when: on_fail

    push-docker:
        executor:
            name: default
        steps:
        - checkout
        - setup_remote_docker
        - run: make build-image
        - run: make test-image
        - run: bash scripts/push-docker.sh
        - run:
            name: Re-run Docker Push if fail
            command: |
                sleep 20
                bash scripts/push-docker.sh
            when: on_fail

    test:
        executor:
          name: default
        steps:
          - checkout
          - run: make test

    release:
      executor: default
      steps:
        - checkout
        - run:
            command: |
              make deps
              make release

workflows:
  version: 2
  ci-build:
    jobs:
    - check-boilerplate
    - test
    - push-docker-pr:
        context: matterbuild-docker
        requires:
          - test
          - check-boilerplate
  publish-github-release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
  master-build:
    jobs:
      - check-boilerplate:
          filters:
            branches:
              only:
                - master
      - test:
          filters:
            branches:
              only:
                - master
      - push-docker:
          context: matterbuild-docker
          requires:
            - test
            - check-boilerplate
          filters:
            branches:
              only:
                - master
  tag-builds:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - check-boilerplate:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - push-docker:
          context: matterbuild-docker
          requires:
            - test
            - check-boilerplate
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/