version: 2.1
executors:
  default:
    docker:
    - image: cimg/go:1.17.4

aliases:
- &restore_cache
  restore_cache:
    key: go-mod-v1-{{ checksum "go.sum" }}
- &save_cache
  save_cache:
    key: go-mod-v1-{{ checksum "go.sum" }}
    paths:
      - "/go/pkg/mod"

jobs:
    check-boilerplate:
      executor:
        name: default
      steps:
      - checkout
      - run: ./scripts/verify-boilerplate.sh

    push-docker-pr:
        executor:
            name: default
        steps:
        - checkout
        - setup_remote_docker
        - run: make build-image
        - run: make test-image
        - run: ./scripts/push-docker-pr.sh
        - run:
            name: Re-run Docker Push if fail
            command: |
                sleep 20
                ./scripts/push-docker-pr.sh
            when: on_fail

    push-docker:
        executor:
            name: default
        steps:
        - checkout
        - setup_remote_docker
        - run: make build-image
        - run: make test-image
        - run: ./scripts/push-docker.sh
        - run:
            name: Re-run Docker Push if fail
            command: |
                sleep 20
                ./scripts/push-docker.sh
            when: on_fail

    test:
        executor:
          name: default
        steps:
          - checkout
          - run: make test

workflows:
  version: 2
  ci-build:
    jobs:
    - check-boilerplate
    - test
    - push-docker-pr:
        context: matterbuild-docker
        requires:
          - test
          - check-boilerplate
