// Copyright (c) 2020-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.
//

//+build e2e

package e2e

var correctSlackUsers map[string]string = map[string]string{
	"vocre@3ssly.com":        "j",
	"foo@bar.com":            "james",
	"bar@baz.com":            "lindsay2",
	"bar2@baz.com":           "lindsay",
	"bar3@baz.com":           "lindsay3",
	"buzz@fuzz.com":          "lindsay.b",
	"cheease@sauce.com":      "linds.b",
	"lorem@ispum.com":        "linds.abc",
	"wow@no.com":             "jason-guest",
	"antoher-email@foo.com":  "lindsay.test",
	"bu@ldsj.com":            "guest3",
	"dfsa@lkjlkjl.cc":        "linds.123",
	"wow@gjds.com":           "jason2",
	"dfwed@shdfrklasers.com": "mike",
	"oupouwj@lkouid.gov":     "asaadmahmood",
	"klkklljk@jdou.com":      "asaad",
	"illllll@muttermost.com": "jason_7",
	"kdjfkdjf@klklk.com":     "jason_3",
	"wizard@warrior.cc":      "jason_15",
	"wizard@bard.com":        "jason_2",
	"kdjfdkj@lllll.com":      "jason_8",
	"kklopij@kk.cm":          "jason_13",
	"kdjfkdj@kdjfdk.com":     "jason_12",
	"ppppp@ooo.ooo":          "jason_14",
	"mooooo@mooo.ooo":        "jason_10",
	"wwwwww@mooo.ooo":        "jason_5",
	"jjjjj@foo.com":          "jason_16",
	"vzarq@zouiu.com":        "jason_4",
	"ungkc@uxwz9.com":        "jason_11",
	"fidpk@7imp6.com":        "jason_6",
	"zkc3e@j3co9.com":        "jason_17",
	"czqsx@zqo6n.com":        "jason_24",
	"rxrsg@qrgob.com":        "blaisjc",
	"2m5hl@12ghe.com":        "michaelandrewgamble",
	"93cln@vpg6w.com":        "kwiersgalla",
	"xhy8a@ac9wf.com":        "katie",
	"jiabs@lqxon.com":        "mike_test3",
	"vcy9k@asotd.com":        "katie_test2",
	"pnk9d@szyfe.com":        "christopher_slack",
	"qlyct@xltoq.com":        "mike_test7",
	"h3npd@fpesk.com":        "mike_test20",
	"tetyq@gva9h.com":        "mike_guest",
	"sih1a@47toc.com":        "mike_guest1",
	"hnsfs@qzpwi.com":        "mike529",
	"fe4yu@tud4y.com":        "mike974",
	"wldbi@m2wiz.com":        "mike670",
	"03mgj@unedj.com":        "mike_test9",
	"ukwl1@04wnp.com":        "mike_fulluser",
	"nlgkr@mwo84.com":        "mike_guestuser",
}

var correctMattermostUsers map[string]string = map[string]string{
	"user-5@sample.mattermost.com":   "aaron.medina",
	"user-7@sample.mattermost.com":   "aaron.peterson",
	"user-4@sample.mattermost.com":   "anne.stone",
	"appsbot@localhost":              "appsbot",
	"user-12@sample.mattermost.com":  "ashley.berry",
	"channelexport@localhost":        "channelexport",
	"user-6@sample.mattermost.com":   "christina.wilson",
	"user-11@sample.mattermost.com":  "craig.reed",
	"user-8@sample.mattermost.com":   "diana.wells",
	"user-14@sample.mattermost.com":  "emily.meyer",
	"guest@sample.mattermost.com":    "guest",
	"user-3@sample.mattermost.com":   "jack.wheeler",
	"user-9@sample.mattermost.com":   "karen.austin",
	"mattermost-advisor@localhost":   "mattermost-advisor",
	"playbook@localhost":             "playbook",
	"user-10@sample.mattermost.com":  "robert.ward",
	"user-13@sample.mattermost.com":  "samuel.palmer",
	"user-2@sample.mattermost.com":   "samuel.tucker",
	"surveybot@localhost":            "surveybot",
	"sysadmin@sample.mattermost.com": "sysadmin",
	"user-1@sample.mattermost.com":   "user-1",
}
