---
name: ci
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/.test.yml
  test-release-deps:
    runs-on: ubuntu-latest
    container:
      image: golang:1.21.11-bookworm
    env:
      GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: ci/install-release-dependencies
        run: make deps
  push-docker:
    uses: ./.github/workflows/.docker-push.yml
    with:
      is_pr: "${{ github.ref != 'refs/heads/main' }}"
    secrets: inherit
    needs: [test]
